dependencies:
  - 'OpenZeppelin/openzeppelin-contracts@4.5.0'
  - 'smartcontractkit/chainlink-brownie-contracts@0.4.0'
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

networks:
  # Setting default to mainnet-fork, because we are gonna use it the most
  rinkeby:
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    link_token: '0x01be23585060835e02b77ef475b0cc51aa1e0709'
    keyHash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 10000000000000000000 # 0.25 $LINK
    subId: 1849
    verify: True
  development:
    key_hash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 10000000000000000000 # 0.25 $LINK